#!/bin/sh
set -e


# Lösche alte .sources-Dateien
for f in \
	/etc/apt/sources.list.d/home:guideos:universe.sources \
	/etc/apt/sources.list.d/home:guideos:trixie.sources \
	/etc/apt/sources.list.d/home:guideos:cinnamon-trixie.sources
do
	if [ -e "$f" ]; then
		echo "Entferne $f ..."
		rm -f "$f"
	fi
done

# Setze Apt::Install-Recommends auf true
echo "Setze Apt::Install-Recommends auf true in /etc/apt/apt.conf.d/99norecommends ..."
echo 'Apt::Install-Recommends "true";' > /etc/apt/apt.conf.d/99norecommends

exit 0
